# Please see https://dash.applovin.com/documentation/mediation/unreal/mediation-adapters/ios for integrating mediated networks.
# Sources
source 'https://cdn.cocoapods.org/'

# Settings
inhibit_all_warnings!

pod 'AppLovinSDK'
pod 'Google-Mobile-Ads-SDK'