# Please see https://developers.applovin.com/en/defold/preparing-mediated-networks#ios for integrating mediated networks.
# Sources
source 'https://cdn.cocoapods.org/'

# Settings
inhibit_all_warnings!

pod 'AppLovinSDK', '12.2.0'
